[package]
name = "void"
version = "0.1.0"
authors = ["hans.vanmoer <hans.vanmoer@formica.digital>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
